from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Project_Test_Page(object):
    def setupUi(self, Project_Test_Page):
        Project_Test_Page.setObjectName("Project_Test_Page")
        Project_Test_Page.resize(815, 506)
        self.centralwidget = QtWidgets.QWidget(Project_Test_Page)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_Aeration = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Aeration.sizePolicy().hasHeightForWidth())
        self.btn_Aeration.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btn_Aeration.setFont(font)
        self.btn_Aeration.setObjectName("btn_Aeration")
        self.verticalLayout_8.addWidget(self.btn_Aeration)
        self.lbl_int_Aeration = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_int_Aeration.sizePolicy().hasHeightForWidth())
        self.lbl_int_Aeration.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_int_Aeration.setFont(font)
        self.lbl_int_Aeration.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_int_Aeration.setObjectName("lbl_int_Aeration")
        self.verticalLayout_8.addWidget(self.lbl_int_Aeration)
        self.slider_int_Aeration = QtWidgets.QSlider(self.centralwidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.slider_int_Aeration.setFont(font)
        self.slider_int_Aeration.setMaximum(100)
        self.slider_int_Aeration.setProperty("value", 100)
        self.slider_int_Aeration.setOrientation(QtCore.Qt.Horizontal)
        self.slider_int_Aeration.setObjectName("slider_int_Aeration")
        self.verticalLayout_8.addWidget(self.slider_int_Aeration)
        self.gridLayout.addLayout(self.verticalLayout_8, 1, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_Chauffage = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Chauffage.sizePolicy().hasHeightForWidth())
        self.btn_Chauffage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btn_Chauffage.setFont(font)
        self.btn_Chauffage.setObjectName("btn_Chauffage")
        self.verticalLayout_5.addWidget(self.btn_Chauffage)
        self.lbl_int_Chauffage = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_int_Chauffage.sizePolicy().hasHeightForWidth())
        self.lbl_int_Chauffage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_int_Chauffage.setFont(font)
        self.lbl_int_Chauffage.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_int_Chauffage.setObjectName("lbl_int_Chauffage")
        self.verticalLayout_5.addWidget(self.lbl_int_Chauffage)
        self.slider_int_Chauffage = QtWidgets.QSlider(self.centralwidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.slider_int_Chauffage.setFont(font)
        self.slider_int_Chauffage.setMaximum(100)
        self.slider_int_Chauffage.setProperty("value", 100)
        self.slider_int_Chauffage.setOrientation(QtCore.Qt.Horizontal)
        self.slider_int_Chauffage.setObjectName("slider_int_Chauffage")
        self.verticalLayout_5.addWidget(self.slider_int_Chauffage)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btn_Humid = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Humid.sizePolicy().hasHeightForWidth())
        self.btn_Humid.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btn_Humid.setFont(font)
        self.btn_Humid.setObjectName("btn_Humid")
        self.verticalLayout_9.addWidget(self.btn_Humid)
        self.lbl_int_Humid = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_int_Humid.sizePolicy().hasHeightForWidth())
        self.lbl_int_Humid.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_int_Humid.setFont(font)
        self.lbl_int_Humid.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_int_Humid.setObjectName("lbl_int_Humid")
        self.verticalLayout_9.addWidget(self.lbl_int_Humid)
        self.slider_int_Humid = QtWidgets.QSlider(self.centralwidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.slider_int_Humid.setFont(font)
        self.slider_int_Humid.setMaximum(100)
        self.slider_int_Humid.setProperty("value", 100)
        self.slider_int_Humid.setOrientation(QtCore.Qt.Horizontal)
        self.slider_int_Humid.setObjectName("slider_int_Humid")
        self.verticalLayout_9.addWidget(self.slider_int_Humid)
        self.gridLayout.addLayout(self.verticalLayout_9, 2, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btn_LED = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_LED.sizePolicy().hasHeightForWidth())
        self.btn_LED.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btn_LED.setFont(font)
        self.btn_LED.setObjectName("btn_LED")
        self.verticalLayout_6.addWidget(self.btn_LED)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.btn_Dehumid = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Dehumid.sizePolicy().hasHeightForWidth())
        self.btn_Dehumid.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btn_Dehumid.setFont(font)
        self.btn_Dehumid.setObjectName("btn_Dehumid")
        self.verticalLayout_10.addWidget(self.btn_Dehumid)
        self.lbl_int_Dehumid = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_int_Dehumid.sizePolicy().hasHeightForWidth())
        self.lbl_int_Dehumid.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_int_Dehumid.setFont(font)
        self.lbl_int_Dehumid.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_int_Dehumid.setObjectName("lbl_int_Dehumid")
        self.verticalLayout_10.addWidget(self.lbl_int_Dehumid)
        self.slider_int_Dehumid = QtWidgets.QSlider(self.centralwidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.slider_int_Dehumid.setFont(font)
        self.slider_int_Dehumid.setMaximum(100)
        self.slider_int_Dehumid.setProperty("value", 100)
        self.slider_int_Dehumid.setOrientation(QtCore.Qt.Horizontal)
        self.slider_int_Dehumid.setObjectName("slider_int_Dehumid")
        self.verticalLayout_10.addWidget(self.slider_int_Dehumid)
        self.gridLayout.addLayout(self.verticalLayout_10, 2, 1, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btn_Lum_Ext = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Lum_Ext.sizePolicy().hasHeightForWidth())
        self.btn_Lum_Ext.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btn_Lum_Ext.setFont(font)
        self.btn_Lum_Ext.setObjectName("btn_Lum_Ext")
        self.verticalLayout_7.addWidget(self.btn_Lum_Ext)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_DEL_Fan = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_DEL_Fan.sizePolicy().hasHeightForWidth())
        self.btn_DEL_Fan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btn_DEL_Fan.setFont(font)
        self.btn_DEL_Fan.setObjectName("btn_DEL_Fan")
        self.verticalLayout_4.addWidget(self.btn_DEL_Fan)
        self.lbl_int_DEL_Fan = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_int_DEL_Fan.sizePolicy().hasHeightForWidth())
        self.lbl_int_DEL_Fan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_int_DEL_Fan.setFont(font)
        self.lbl_int_DEL_Fan.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_int_DEL_Fan.setObjectName("lbl_int_DEL_Fan")
        self.verticalLayout_4.addWidget(self.lbl_int_DEL_Fan)
        self.slider_int_DEL_Fan = QtWidgets.QSlider(self.centralwidget)
        self.slider_int_DEL_Fan.setMaximum(100)
        self.slider_int_DEL_Fan.setProperty("value", 100)
        self.slider_int_DEL_Fan.setOrientation(QtCore.Qt.Horizontal)
        self.slider_int_DEL_Fan.setObjectName("slider_int_DEL_Fan")
        self.verticalLayout_4.addWidget(self.slider_int_DEL_Fan)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_Box_Fan = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Box_Fan.sizePolicy().hasHeightForWidth())
        self.btn_Box_Fan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btn_Box_Fan.setFont(font)
        self.btn_Box_Fan.setObjectName("btn_Box_Fan")
        self.verticalLayout_2.addWidget(self.btn_Box_Fan)
        self.lbl_int_Box_Fan = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_int_Box_Fan.sizePolicy().hasHeightForWidth())
        self.lbl_int_Box_Fan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_int_Box_Fan.setFont(font)
        self.lbl_int_Box_Fan.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_int_Box_Fan.setObjectName("lbl_int_Box_Fan")
        self.verticalLayout_2.addWidget(self.lbl_int_Box_Fan)
        self.slider_int_Box_Fan = QtWidgets.QSlider(self.centralwidget)
        self.slider_int_Box_Fan.setMaximum(100)
        self.slider_int_Box_Fan.setProperty("value", 100)
        self.slider_int_Box_Fan.setOrientation(QtCore.Qt.Horizontal)
        self.slider_int_Box_Fan.setObjectName("slider_int_Box_Fan")
        self.verticalLayout_2.addWidget(self.slider_int_Box_Fan)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_Opt_Fan = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Opt_Fan.sizePolicy().hasHeightForWidth())
        self.btn_Opt_Fan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btn_Opt_Fan.setFont(font)
        self.btn_Opt_Fan.setObjectName("btn_Opt_Fan")
        self.verticalLayout_3.addWidget(self.btn_Opt_Fan)
        self.lbl_int_Opt_Fan = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_int_Opt_Fan.sizePolicy().hasHeightForWidth())
        self.lbl_int_Opt_Fan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_int_Opt_Fan.setFont(font)
        self.lbl_int_Opt_Fan.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_int_Opt_Fan.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_int_Opt_Fan.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_int_Opt_Fan.setObjectName("lbl_int_Opt_Fan")
        self.verticalLayout_3.addWidget(self.lbl_int_Opt_Fan)
        self.slider_int_Opt_Fan = QtWidgets.QSlider(self.centralwidget)
        self.slider_int_Opt_Fan.setMaximum(100)
        self.slider_int_Opt_Fan.setProperty("value", 100)
        self.slider_int_Opt_Fan.setOrientation(QtCore.Qt.Horizontal)
        self.slider_int_Opt_Fan.setObjectName("slider_int_Opt_Fan")
        self.verticalLayout_3.addWidget(self.slider_int_Opt_Fan)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        Project_Test_Page.setCentralWidget(self.centralwidget)


        self.retranslateUi(Project_Test_Page)
        self.setupEvents()

        QtCore.QMetaObject.connectSlotsByName(Project_Test_Page)

    def setupEvents(self):
        self.btn_LED.clicked.connect(self.btn_LED_Clicked)
        self.btn_Lum_Ext.clicked.connect(self.btn_Lum_Ext_Clicked)
        self.btn_Humid.clicked.connect(self.btn_Humid_Clicked)
        self.slider_int_Humid.valueChanged.connect(self.slider_int_Humid_Changed)
        self.btn_Dehumid.clicked.connect(self.btn_Dehumid_Clicked)
        self.slider_int_Dehumid.valueChanged.connect(self.slider_int_Dehumid_Changed)
        self.btn_Aeration.clicked.connect(self.btn_Aeration_Clicked)
        self.slider_int_Aeration.valueChanged.connect(self.slider_int_Aeration_Changed)
        self.btn_Chauffage.clicked.connect(self.btn_Chauffage_Clicked)
        self.slider_int_Chauffage.valueChanged.connect(self.slider_int_Chauffage_Changed)
        self.btn_DEL_Fan.clicked.connect(self.btn_DEL_Fan_Clicked)
        self.slider_int_DEL_Fan.valueChanged.connect(self.slider_int_DEL_Fan_Changed)
        self.btn_Box_Fan.clicked.connect(self.btn_Box_Fan_Clicked)
        self.slider_int_Box_Fan.valueChanged.connect(self.slider_int_Box_Fan_Changed)
        self.btn_Opt_Fan.clicked.connect(self.btn_Opt_Fan_Clicked)
        self.slider_int_Opt_Fan.valueChanged.connect(self.slider_int_Opt_Fan_Changed)


    def retranslateUi(self, Project_Test_Page):
        _translate = QtCore.QCoreApplication.translate
        Project_Test_Page.setWindowTitle(_translate("Project_Test_Page", "Project_Test_Page"))
        self.btn_Aeration.setText(_translate("Project_Test_Page", "Aération On/Off"))
        self.lbl_int_Aeration.setText(_translate("Project_Test_Page", "100"))
        self.btn_Chauffage.setText(_translate("Project_Test_Page", "Chauffage On/Off"))
        self.lbl_int_Chauffage.setText(_translate("Project_Test_Page", "100"))
        self.btn_Humid.setText(_translate("Project_Test_Page", "Humidificateur On/Off"))
        self.lbl_int_Humid.setText(_translate("Project_Test_Page", "100"))
        self.btn_LED.setText(_translate("Project_Test_Page", "LED On/Off"))
        self.btn_Dehumid.setText(_translate("Project_Test_Page", "Déshumidificateur On/Off"))
        self.lbl_int_Dehumid.setText(_translate("Project_Test_Page", "100"))
        self.btn_Lum_Ext.setText(_translate("Project_Test_Page", "Lum. Ext. On/Off"))
        self.btn_DEL_Fan.setText(_translate("Project_Test_Page", "Fan DEL On/Off"))
        self.lbl_int_DEL_Fan.setText(_translate("Project_Test_Page", "100"))
        self.btn_Box_Fan.setText(_translate("Project_Test_Page", "Fan Boitier On/Off"))
        self.lbl_int_Box_Fan.setText(_translate("Project_Test_Page", "100"))
        self.btn_Opt_Fan.setText(_translate("Project_Test_Page", "Fan opt. On/Off"))
        self.lbl_int_Opt_Fan.setText(_translate("Project_Test_Page", "100"))

    def btn_LED_Clicked(self):
        '''
        import RPi.GPIO as GPIO         #Sera necessaire pour activer les GPIOs
        import time

        GPIO.setmode(GPIO.BOARD)   # BOARD ou BCM (BCM  = GPIO number, board = Physical number)
        GPIO.setup(#Pin,GPIO.OUT)

        GPIO.output(#Pin,1)
        time.sleep(5)
        GPIO.cleanup()
        '''
        print("Ayyy lmao   --   LED ON! ..or off, just take a look really")

    def btn_Lum_Ext_Clicked(self):
        print("Lumiere Externe Allumee")

    def btn_Humid_Clicked(self):
        print("Humidificateur On!")

    def btn_Dehumid_Clicked(self):
        print("Deshumidificateur off!?")

    def btn_Aeration_Clicked(self):
        print("Aération démarrée")

    def btn_Chauffage_Clicked(self):
        print("Chaleur. Chaud. Energie Thermique.")

    def btn_DEL_Fan_Clicked(self):
        print("Vent sur lumiere")

    def btn_Box_Fan_Clicked(self):
        print("vent dans la boite?")

    def btn_Opt_Fan_Clicked(self):
        print("J'opte pour le vent ?")

    def slider_int_Humid_Changed(self):
        try:
            self.lbl_int_Humid.setText(str(self.slider_int_Humid.value()))
        except Exception as err:
            print(str(err))
    def slider_int_Dehumid_Changed(self):
        try:
            self.lbl_int_Dehumid.setText(str(self.slider_int_Dehumid.value()))
        except Exception as err:
            print(str(err))
    def slider_int_Aeration_Changed(self):
        try:
            self.lbl_int_Aeration.setText(str(self.slider_int_Aeration.value()))
        except Exception as err:
            print(str(err))
    def slider_int_Chauffage_Changed(self):
        try:
            self.lbl_int_Chauffage.setText(str(self.slider_int_Chauffage.value()))
        except Exception as err:
            print(str(err))
    def slider_int_DEL_Fan_Changed(self):
        try:
            self.lbl_int_DEL_Fan.setText(str(self.slider_int_DEL_Fan.value()))
        except Exception as err:
            print(str(err))
    def slider_int_Box_Fan_Changed(self):
        try:
            self.lbl_int_Box_Fan.setText(str(self.slider_int_Box_Fan.value()))
        except Exception as err:
            print(str(err))
    def slider_int_Opt_Fan_Changed(self):
        try:
            self.lbl_int_Opt_Fan.setText(str(self.slider_int_Opt_Fan.value()))
        except Exception as err:
            print(str(err))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Project_Test_Page = QtWidgets.QMainWindow()
    ui = Ui_Project_Test_Page()
    ui.setupUi(Project_Test_Page)
    Project_Test_Page.show()
    sys.exit(app.exec_())
